version: '3'
services:
  db:
    container_name: psqlhost
    image: postgres
    environment:
      POSTGRES_DB: gousers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:      
      - "5432:5432"
  redis:  
    container_name: redishost
    image: redis:alpine     
  app:
    container_name: app
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
      - .:/go/test/res
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      REDIS_URL: redishost:6379